name: nlp2
channels:
  - defaults
dependencies:
  - python=3.10
  - scikit-learn
  - pip
  - pytorch
  - ipykernel
  - torchvision
  - torchaudio
  - numpy
  - matplotlib
  - pandas
  - seaborn
  - notebook
  - jupyter
  - ipywidgets
  - pip:
      - datasets
      - transformers>=4.41
      - accelerate>=0.26.0
      - nltk
      - kagglehub
      - tqdm
      - sentencepiece
      - sacrebleu
      - rouge-score
      - kagglehub
      - langdetect
      - sentence_transformers

